apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uda-frontend
  name: uda-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uda-frontend
  template:
    metadata:
      labels:
        app: uda-frontend
    spec:
      containers:
      - name: uda-frontend
        image: soonnguyen108/udagram-frontend:df1048c
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
